// Add category
export const ADD_CATEGORY_START = 'ADD_CATEGORY_START'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE'

// Get categories
export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

// Edit category
export const EDIT_CATEGORY_START = 'EDIT_CATEGORY_START'
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS'
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE'

// Delete category
export const DEL_CATEGORY_START = 'DEL_CATEGORY_START'
export const DEL_CATEGORY_SUCCESS = 'DEL_CATEGORY_SUCCESS'
export const DEL_CATEGORY_FAILURE = 'DEL_CATEGORY_FAILURE'