// Add movie
export const ADD_MOVIE_START = 'ADD_MOVIE_START'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE'

// Get movies
export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'

// Get movies by category
export const GET_MOVIES_BY_CATEGORY_START = 'GET_MOVIES_BY_CATEGORY_START'
export const GET_MOVIES_BY_CATEGORY_SUCCESS = 'GET_MOVIES_BY_CATEGORY_SUCCESS'
export const GET_MOVIES_BY_CATEGORY_FAILURE = 'GET_MOVIES_BY_CATEGORY_FAILURE'

// Get link movie
export const GET_LINK_MOVIE_START = 'GET_LINK_MOVIE_START'
export const GET_LINK_MOVIE_SUCCESS = 'GET_LINK_MOVIE_SUCCESS'
export const GET_LINK_MOVIE_FAILURE = 'GET_LINK_MOVIE_FAILURE'

// Search movies
export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START'
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE'

// Update movie
export const UPDATE_MOVIE_START = 'UPDATE_MOVIE_START'
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS'
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE'

// Delete movie
export const DELETE_MOVIE_START = 'DELETE_MOVIE_START'
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS'
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE'


